Repository cjolowicz/nox-poetry, pull requests merged in 2021-01, with the labels that each got.

#224 Security update to py 1.10.0 and cryptography 3.3.1
  poetry.lock
Labels: dependencies

#233 Decode pyproject.toml as UTF-8 regardless of system locale
  src/nox_poetry/poetry.py
Labels: bug

#234 Add test for non-ASCII characters in pyproject.toml
  tests/unit/test_poetry.py
Labels: testing
